# MC服务器管理插件配置文件

# 服务器状态检查间隔（分钟）
checkInterval: 1

# 每个群可添加的最大服务器数量
maxServers: 10

# 推送消息格式
pushFormat:
  join: '【MC服务器推送】{player}已进入{server}'
  leave: '【MC服务器推送】{player}已下线{server}'
  newPlayer: '【MC服务器推送】发现新玩家{player}进入服务器{server}'
  serverOnline: '【MC服务器推送】{server}已上线'
  serverOffline: '【MC服务器推送】{server}已离线'

# API超时时间（秒）
apiTimeout: 5

# 验证功能全局配置
auth:
  apiUrl: 'https://uapis.cn/api/mcinfo'  # 验证API地址
  requestTimeout: 10000  # 验证请求超时时间（毫秒）
  maxUsernameLength: 16  # MC用户名最大长度
  debug: false  # 是否开启调试模式