# MCTool Plugin 配置文件

# 服务器状态检查配置
checkInterval: 5  # 检查间隔（分钟）
maxServers: 10    # 每个群可添加的最大服务器数量
apiTimeout: 10    # API请求超时时间（秒）

# 推送消息格式配置
pushFormat:
  # 玩家动态推送
  join: "玩家 {player} 加入了 {server} 服务器"
  leave: "玩家 {player} 离开了 {server} 服务器"
  newPlayer: "欢迎新玩家 {player} 首次加入 {server} 服务器！"
  
  # 服务器状态推送
  serverOnline: "{server} 服务器已上线"
  serverOffline: "{server} 服务器已离线"

# 验证功能配置
auth:
  apiUrl: "https://api.mojang.com"  # 验证服务器API地址
  requestTimeout: 5000              # 验证请求超时时间（毫秒）
  maxUsernameLength: 16            # MC用户名最大长度限制
  debug: false                     # 是否开启调试模式 