#不知道的不要乱改

# API配置
apis:
  - name: mcsrvstat
    url: https://api.mcsrvstat.us/3/{host}:{port}
    timeout: 30
    maxRetries: 3
    retryDelay: 1000
    parser:
      online: online
      players:
        online: players.online
        max: players.max
        list: players.list[].name
      version: version.name_clean
      motd: motd.clean[]

  - name: mcstatus
    url: https://api.mcstatus.io/v2/status/java/{host}:{port}
    timeout: 30
    maxRetries: 3
    retryDelay: 1000
    parser:
      online: online
      players:
        online: players.online
        max: players.max
        list: players.list[].name_clean
      version: version.name_clean
      motd: motd.clean[]

# 定时任务配置
schedule:
  cron: "30 * * * * *"  # 每分钟的第30秒执行
  startupNotify: true   # 是否在机器人启动时发送服务器状态推送
  retryDelay: 5000      # 重试等待时间（毫秒）

# 数据存储路径
dataPath: data/mctool

# 默认群组配置
defaultGroup:
  enabled: false
  serverStatusPush: false
  newPlayerAlert: false

# 验证配置
verification:
  enabled: false
  expireTime: 86400
  maxRequests: 5