# MCTool Plugin 配置文件

# 服务器状态检查配置
checkInterval: '*/1 * * * *'  # cron表达式，默认每分钟检查一次
maxServers: 10    # 每个群可添加的最大服务器数量

# API 配置
apiTimeout: 30  # API 超时时间（秒）
maxRetries: 3   # 最大重试次数
retryDelay: 1000  # 重试延迟（毫秒）

# 推送消息格式
pushFormat:
  join: "{player} 加入了服务器 {server}"
  leave: "{player} 离开了服务器 {server}"
  newPlayer: "新玩家 {player} 加入了服务器 {server}"
  serverOnline: "服务器 {server} 已上线"
  serverOffline: "服务器 {server} 已离线"

# 数据文件配置
dataFiles:
  - servers      # 服务器配置
  - current      # 当前状态
  - historical   # 历史记录
  - changes      # 变动记录
  - subscriptions  # 订阅配置