# MCTool Plugin 默认配置文件
#请不要随意修改

# API配置
apis:
  - name: mcsrvstat
    url: https://api.mcsrvstat.us/3/{host}:{port}
    timeout: 30  # 超时时间（秒）
    maxRetries: 3  # 最大重试次数
    retryDelay: 1000  # 重试延迟（毫秒）
    parser:  # 解析配置
      online: online  # 在线状态字段
      players:  # 玩家相关字段
        online: players.online  # 在线人数字段
        max: players.max  # 最大人数字段
        list: players.list[].name  # 玩家列表字段
      version: version.name_clean  # 版本字段
      motd: motd.clean[]  # MOTD字段

  - name: mcstatus
    url: https://api.mcstatus.io/v2/status/java/{host}:{port}
    timeout: 30  # 超时时间（秒）
    maxRetries: 3  # 最大重试次数
    retryDelay: 1000  # 重试延迟（毫秒）
    parser:  # 解析配置
      online: online  # 在线状态字段
      players:  # 玩家相关字段
        online: players.online  # 在线人数字段
        max: players.max  # 最大人数字段
        list: players.list[].name_clean  # 玩家列表字段
      version: version.name_clean  # 版本字段
      motd: motd.clean[]  # MOTD字段

# 定时任务配置
schedule:
  # 定时任务cron表达式，默认每分钟的第30秒执行
  cron: '30 * * * * *'
  # 启动时是否发送通知
  startupNotify: true
  # 重试等待时间(毫秒)
  retryDelay: 5000

# 数据存储路径
dataPath: 'data/mctool'

# 默认群组推送配置
defaultGroup:
  # 是否启用默认群组
  enabled: false
  # 是否推送服务器状态
  serverStatusPush: false
  # 是否推送新玩家提醒
  newPlayerAlert: false

# 验证配置
verification:
  # 是否启用验证
  enabled: false
  # 验证过期时间(秒)
  expireTime: 86400
  # 最大请求次数
  maxRequests: 5

# 皮肤渲染配置
skin:
  # 是否使用3D渲染
  use3D: false
  # 渲染方案选择 (1: 行走视图[推荐], 2: 站立视图)
  renderType: 1
  # 渲染方案一配置（行走视图）
  render1:
    # 渲染服务器地址
    server: 'https://skin2.qxml.ltd' # 3D渲染服务器地址 公共API：https://skin2.qxml.ltd
    # 图片清晰度
    definition: 1.5 # 图片清晰度 推荐在1.5-2.5之间
    # 是否透明背景
    transparent: true # 是否透明背景 推荐开启
  # 渲染方案二配置（站立视图）
  render2:
    # 渲染服务器地址
    server: 'http://127.0.0.1:3006' # 3D渲染服务器地址 公共API：http://skin.qxml.ltd
    # 渲染接口路径
    endpoint: '/render'
    # 渲染宽度
    width: 300 # 渲染宽度 推荐在300-500之间
    # 渲染高度
    height: 600 